//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authetication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class authenticationEntities1 : DbContext
    {
        public authenticationEntities1()
            : base("name=authenticationEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Foodlist> Foodlists { get; set; }
        public virtual DbSet<TBLUser> TBLUsers { get; set; }
        public virtual DbSet<TBLUserType> TBLUserTypes { get; set; }
    }
}
